import { Resend } from 'resend'

export const resend = new Resend(process.env.RESEND_API_KEY!)

export async function sendDocumentEmail(
  to: string,
  documentType: string,
  documentNumber: string,
  senderName: string,
  pdfContent: string
) {
  return resend.emails.send({
    from: 'SubieSafe <documents@subiesafe.com>',
    to,
    subject: `${documentType} - ${documentNumber} from ${senderName}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: #0f172a; padding: 24px; text-align: center;">
          <h1 style="color: #f59e0b; margin: 0; font-size: 24px;">SubieSafe</h1>
          <p style="color: #94a3b8; margin: 8px 0 0;">AI Paper Trail Engine</p>
        </div>
        <div style="padding: 32px; background: #f8fafc;">
          <h2 style="color: #0f172a;">You have received a formal document</h2>
          <p style="color: #475569;">
            <strong>${senderName}</strong> has sent you a <strong>${documentType}</strong> 
            (Reference: ${documentNumber}) via SubieSafe.
          </p>
          <p style="color: #475569;">
            This document has been formally generated and time-stamped as part of a legal 
            paper trail under the Housing Grants, Construction & Regeneration Act 1996 (HGCRA).
          </p>
          <div style="background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 24px; margin: 24px 0;">
            <pre style="font-family: 'Courier New', monospace; font-size: 12px; color: #1e293b; white-space: pre-wrap;">${pdfContent}</pre>
          </div>
          <p style="color: #94a3b8; font-size: 12px; margin-top: 32px;">
            This document was generated by SubieSafe. For any queries, contact the sender directly.
            SubieSafe documents are time-stamped and stored securely for audit purposes.
          </p>
        </div>
      </div>
    `,
  })
}
