import { NextRequest, NextResponse } from 'next/server'

const DOC_TYPE_LABELS: Record<string, string> = {
  'variation-order': 'Variation Order',
  'delay-notice': 'Delay Notice',
  'payment-notice': 'Payment Notice',
  'pay-less-notice': 'Pay Less Notice',
  'daywork-sheet': 'Daywork Sheet',
  'site-instruction-record': 'Site Instruction Record',
}

function generateHtmlPdf(document: Record<string, unknown>, docType: string): string {
  const docLabel = DOC_TYPE_LABELS[docType] || docType

  const renderValue = (value: unknown): string => {
    if (Array.isArray(value)) {
      if (value.length === 0) return ''
      if (typeof value[0] === 'object') {
        const headers = Object.keys(value[0] as Record<string, unknown>)
        return `<table style="width:100%;border-collapse:collapse;margin:8px 0;font-size:12px;">
          <thead><tr>${headers.map(h => `<th style="background:#0f172a;color:#f8fafc;padding:6px 8px;text-align:left;border:1px solid #e2e8f0;">${h}</th>`).join('')}</tr></thead>
          <tbody>${(value as Record<string, unknown>[]).map(row =>
            `<tr>${headers.map(h => `<td style="padding:6px 8px;border:1px solid #e2e8f0;">${row[h] || ''}</td>`).join('')}</tr>`
          ).join('')}</tbody>
        </table>`
      }
      return `<ul style="margin:4px 0;padding-left:20px;">${value.map(v => `<li style="margin:3px 0;">${v}</li>`).join('')}</ul>`
    }
    return `<span>${value}</span>`
  }

  const skipKeys = ['title', 'documentNumber', 'contractor', 'date', 'project', 'footer', 'signatoryLine', 'siteManagerSignature', 'acknowledgement']

  const rows = Object.entries(document)
    .filter(([key]) => !skipKeys.includes(key))
    .map(([key, value]) => {
      const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())
      return `
        <tr>
          <td style="padding:10px 12px;border:1px solid #e2e8f0;background:#f8fafc;font-weight:600;color:#374151;width:200px;vertical-align:top;font-size:12px;">${label}</td>
          <td style="padding:10px 12px;border:1px solid #e2e8f0;color:#1e293b;font-size:12px;vertical-align:top;">${renderValue(value)}</td>
        </tr>`
    }).join('')

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; color: #1e293b; background: white; }
    @page { size: A4; margin: 20mm; }
  </style>
</head>
<body>
  <div style="border-bottom: 3px solid #f59e0b; padding-bottom: 20px; margin-bottom: 24px;">
    <div style="display: flex; justify-content: space-between; align-items: flex-start;">
      <div>
        <div style="font-size: 11px; color: #94a3b8; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 4px;">SubieSafe</div>
        <h1 style="font-size: 24px; font-weight: 900; color: #0f172a; text-transform: uppercase; letter-spacing: 1px;">${document.title || docLabel}</h1>
        ${document.documentNumber ? `<div style="margin-top: 4px; font-size: 13px; color: #64748b;">Ref: ${document.documentNumber}</div>` : ''}
      </div>
      <div style="text-align: right;">
        <div style="font-weight: 700; color: #0f172a;">${document.contractor || ''}</div>
        <div style="font-size: 12px; color: #64748b; margin-top: 2px;">${document.date || ''}</div>
      </div>
    </div>
    ${document.project ? `<div style="margin-top: 12px; padding: 8px 12px; background: #fef3c7; border-radius: 6px; border: 1px solid #fbbf24;">
      <span style="font-size: 11px; color: #92400e; font-weight: 600;">PROJECT: </span>
      <span style="font-size: 12px; color: #92400e;">${document.project}</span>
    </div>` : ''}
  </div>

  <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
    ${rows}
  </table>

  ${document.signatoryLine || document.siteManagerSignature ? `
  <div style="margin-top: 24px; padding-top: 16px; border-top: 1px solid #e2e8f0;">
    <p style="color: #374151;">${document.signatoryLine || document.siteManagerSignature}</p>
  </div>` : ''}

  ${document.acknowledgement ? `
  <div style="margin-top: 16px; padding: 12px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px;">
    <p style="font-size: 12px; color: #475569; font-style: italic;">${document.acknowledgement}</p>
  </div>` : ''}

  ${document.footer ? `
  <div style="margin-top: 32px; padding-top: 12px; border-top: 2px solid #f59e0b;">
    <p style="font-size: 10px; color: #94a3b8; font-style: italic;">${document.footer}</p>
    <p style="font-size: 10px; color: #94a3b8; margin-top: 4px;">Generated by SubieSafe · subiesafe.com · ${new Date().toISOString()}</p>
  </div>` : ''}
</body>
</html>`
}

export async function POST(req: NextRequest) {
  try {
    const { document, docType } = await req.json()
    const html = generateHtmlPdf(document, docType)

    // Return HTML that can be printed/saved as PDF by browser
    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'X-PDF-Ready': 'true',
      },
    })
  } catch (error) {
    console.error('PDF error:', error)
    return NextResponse.json({ error: 'PDF generation failed' }, { status: 500 })
  }
}
